obj-m += char_driver.o


all:
	make -C /home/user/linux_workspace/kernel_ws/KSRC M=${PWD} modules ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-
clean:
	make -C /home/user/linux_workspace/kernel_ws/KSRC M=${PWD} modules ARCH=arm CROSS_COMPILE=arm-linux-gnueabi-
